### ISSUE TITLE
Remove Duplicate Domains - The domain is used by an attribute rule

### ISSUE THREAD

**Issue by WestonSF** [WestonSF/ArcGISDataToolkit#6]
The following error comes up when a certain domain is trying to be removed:

Reassigning domain on feature class parks_all_tracks from YesNoTxt_1 to YesNoTxt as it is duplicated...
Reassigning domain on feature class parks_all_tracks from YesNoTxt_1 to YesNoTxt as it is duplicated...
Reassigning domain on feature class parks_all_tracks from YesNoTxt_1 to YesNoTxt as it is duplicated...
Removing domain Bollards as not being used...
Removing domain EncroachBuilding as not being used...
ERROR 999999: Error executing function.
The domain is used by an attribute rule.
Failed to execute (DeleteDomain).

Completed script RemoveDuplicateDomains...
Failed to execute (RemoveDuplicateDomains).
Failed at Tue May 27 17:54:30 2014 (Elapsed Time: 20 minutes 56 seconds)

**Comment by moiAK** [comment]
I am still getting this error
